// Location-based route configurations
export const LOCATION_ROUTES = [
  'decatur',
  'alvord',
  'boyd',
  'bridgeport',
  'chico',
  'greenwood',
  'newark',
  'paradise',
  'rhome',
  'bowie',
  'forestburg',
  'montague',
  'nocona',
  'ringgold',
  'denton',
  'aubrey',
  'corinth',
  'highland-village',
  'justin',
  'krugerville',
  'krum',
  'lake-dallas',
  'lakewood-village',
  'little-elm',
  'oak-point',
  'pilot-point',
  'roanoke',
  'sanger',
  'the-colony',
  'azle',
  'fort-worth',
  'bedford',
  'blue-mound',
  'colleyville',
  'dalworthington-gardens',
  'euless',
  'everman',
  'forest-hill',
  'haltom-city',
  'hurst',
  'keller',
  'kennedale',
  'lake-worth',
  'north-richland-hills',
  'pelican-bay',
  'richland-hills',
  'river-oaks',
  'saginaw',
  'sansom-park',
  'watauga',
  'westworth-village',
  'white-settlement',
  'dallas',
  'balch-springs',
  'cockrell-hill',
  'desoto',
  'duncanville',
  'farmers-branch',
  'hutchins',
  'irving',
  'lancaster',
  'university-park',
  'wilmer',
  'addison',
  'highland-park',
  'sunnyvale',
  'allen',
  'anna',
  'blue-ridge',
  'farmersville',
  'lavon',
  'lowry-crossing',
  'lucas',
  'mckinney',
  'melissa',
  'murphy',
  'nevada',
  'parker',
  'princeton',
  'weston',
  // Vancouver Metro Area cities
  'vancouver',
  'burnaby',
  'richmond',
  'surrey',
  'coquitlam',
  'langley',
  'delta',
  'north-vancouver',
  'west-vancouver',
  'new-westminster',
  'port-moody',
  'port-coquitlam',
  'white-rock',
  'maple-ridge',
  'pitt-meadows',
];

// Service route configurations
export const SERVICE_ROUTES = [
  { path: 'website-design', service: 'website-design' },
  { path: 'seo', service: 'seo' },
  { path: 'google-marketing', service: 'google-marketing' },
  { path: 'social-media-marketing', service: 'social-media-marketing' },
  { path: 'videography', service: 'videography' },
  { path: 'virtual-tours', service: 'virtual-tours' },
];

// Redirect configurations
export const REDIRECT_ROUTES = [
  // Homepage variants
  { from: '/home', to: '/' },
  { from: '/preview_page.html', to: '/' },
  { from: '/generative-ai-image-testing', to: '/' },

  // Old /services/* URLs → new service pages  
  { from: '/services/seo', to: '/strategic-seo' },
  { from: '/services/seo/', to: '/strategic-seo' },
  { from: '/services/videography', to: '/videography' },
  { from: '/services/social-media-marketing', to: '/social-media' },

  // Contact page variants (note: /contact redirects TO /contact-us)
  { from: '/contact', to: '/contact-us' },
];
