import { google } from 'googleapis';

/**
 * Initializes the Google Drive API client using credentials from the environment.
 */
const getDriveService = () => {
  const credentialsRaw = process.env.GOOGLE_DRIVE_CREDENTIALS;
  if (!credentialsRaw) {
    console.warn('GOOGLE_DRIVE_CREDENTIALS is not defined. Logging will be skipped.');
    return null;
  }

  try {
    const credentials = JSON.parse(credentialsRaw);
    const auth = new google.auth.GoogleAuth({
      credentials,
      scopes: ['https://www.googleapis.com/auth/drive.file'],
    });

    return google.drive({ version: 'v3', auth });
  } catch (error) {
    console.error('Failed to parse GOOGLE_DRIVE_CREDENTIALS:', error);
    return null;
  }
};

/**
 * Logs the generated agent output to a specified Google Drive folder.
 * 
 * @param filename The desired name for the document (e.g., 'Domain-Strategy-Report.txt').
 * @param content The full text output generated by the AI agent.
 */
export const logToDrive = async (filename: string, content: string): Promise<boolean> => {
  const drive = getDriveService();
  const folderId = process.env.GOOGLE_DRIVE_FOLDER_ID;

  if (!drive || !folderId) {
    console.warn(`Skipping Drive upload for ${filename} due to missing configuration.`);
    return false;
  }

  try {
    const fileMetadata = {
      name: filename,
      parents: [folderId],
    };

    const media = {
      mimeType: 'text/plain',
      body: content,
    };

    console.log(`Uploading ${filename} to Google Drive...`);
    const file = await drive.files.create({
      requestBody: fileMetadata,
      media: media,
      fields: 'id',
    });

    console.log(`Upload successful. File ID: ${file.data.id}`);
    return true;
  } catch (error) {
    console.error('Error logging to Google Drive:', error);
    return false;
  }
};
